spring:
  application:
    name: hhplus
  profiles:
    active: h2
  jpa:
    defer-datasource-initialization: true
    open-in-view: false
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.timezone.default_storage: NORMALIZE_UTC
      hibernate.jdbc.time_zone: UTC

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  override-with-generic-response: false